(function() {var implementors = {};
implementors["libtls"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.pointer.html\">*mut </a><a class=\"struct\" href=\"libtls_sys/struct.tls_config.html\" title=\"struct libtls_sys::tls_config\">tls_config</a>&gt; for <a class=\"struct\" href=\"libtls/config/struct.TlsConfig.html\" title=\"struct libtls::config::TlsConfig\">TlsConfig</a>",synthetic:false,types:["libtls::config::TlsConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.NulError.html\" title=\"struct std::ffi::c_str::NulError\">NulError</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/num/struct.TryFromIntError.html\" title=\"struct core::num::TryFromIntError\">TryFromIntError</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.pointer.html\">*mut </a><a class=\"struct\" href=\"libtls_sys/struct.tls.html\" title=\"struct libtls_sys::tls\">tls</a>&gt; for <a class=\"struct\" href=\"libtls/tls/struct.Tls.html\" title=\"struct libtls::tls::Tls\">Tls</a>",synthetic:false,types:["libtls::tls::Tls"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
