(function() {var implementors = {};
implementors["libtls"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.NulError.html\" title=\"struct std::ffi::c_str::NulError\">NulError</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/core/num/struct.TryFromIntError.html\" title=\"struct core::num::TryFromIntError\">TryFromIntError</a>&gt; for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>",synthetic:false,types:["std::io::error::Error"]},];
implementors["tokio_libtls"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"tokio_libtls/prelude/error/enum.TlsError.html\" title=\"enum tokio_libtls::prelude::error::TlsError\">TlsError</a>&gt; for <a class=\"enum\" href=\"tokio_libtls/error/enum.AsyncTlsError.html\" title=\"enum tokio_libtls::error::AsyncTlsError\">AsyncTlsError</a>",synthetic:false,types:["tokio_libtls::error::AsyncTlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"tokio_libtls/error/enum.AsyncTlsError.html\" title=\"enum tokio_libtls::error::AsyncTlsError\">AsyncTlsError</a>",synthetic:false,types:["tokio_libtls::error::AsyncTlsError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"tokio_libtls/error/enum.AsyncTlsError.html\" title=\"enum tokio_libtls::error::AsyncTlsError\">AsyncTlsError</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>",synthetic:false,types:["std::io::error::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()