(function() {var implementors = {};
implementors["libtls"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"libtls/config/struct.TlsConfigBuilder.html\" title=\"struct libtls::config::TlsConfigBuilder\">TlsConfigBuilder</a>",synthetic:false,types:["libtls::config::TlsConfigBuilder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"libtls/error/enum.TlsError.html\" title=\"enum libtls::error::TlsError\">TlsError</a>",synthetic:false,types:["libtls::error::TlsError"]},];
implementors["libtls_sys"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"libtls_sys/struct.max_align_t.html\" title=\"struct libtls_sys::max_align_t\">max_align_t</a>",synthetic:false,types:["libtls_sys::max_align_t"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"libtls_sys/struct.tls.html\" title=\"struct libtls_sys::tls\">tls</a>",synthetic:false,types:["libtls_sys::tls"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"libtls_sys/struct.tls_config.html\" title=\"struct libtls_sys::tls_config\">tls_config</a>",synthetic:false,types:["libtls_sys::tls_config"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"libtls_sys/struct.__va_list_tag.html\" title=\"struct libtls_sys::__va_list_tag\">__va_list_tag</a>",synthetic:false,types:["libtls_sys::__va_list_tag"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
